#!/usr/bin/env bash

#
#  Copyright (c) 2016 CA. All rights reserved.
#
#  This software may be modified and distributed under the terms
#  of the MIT license. See the LICENSE file for details.
#

export IMAGE_TAG=${IMAGE_TAG:-latest}
export IMAGE=${IMAGE:-caapimcollab/mobile-api-gateway:${IMAGE_TAG}}

export MAG_HOSTNAME="${MAG_HOSTNAME:-mag}"
export OTK_HOSTNAME="${MAG_HOSTNAME}"

export BUNDLE_TEMPLATE_HOSTNAME="${MAG_HOSTNAME}"

export BUNDLE_TEMPLATE_MAG_DATABASE_HOST="${MAG_DATABASE_HOST:-mysqldb}"
export BUNDLE_TEMPLATE_MAG_DATABASE_PORT="${MAG_DATABASE_PORT:-3306}"
export BUNDLE_TEMPLATE_MAG_DATABASE_USER="${MAG_DATABASE_USER:-db_admin}"
export BUNDLE_TEMPLATE_MAG_DATABASE_PASSWORD="${MAG_DATABASE_PASSWORD:-"UTWtziFHF0xgng=="}"
export BUNDLE_TEMPLATE_MAG_DATABASE_NAME="${MAG_DATABASE_NAME:-otk_db}"
export BUNDLE_TEMPLATE_MAG_DATABASE_TYPE="${MAG_DATABASE_TYPE:-mysql}"
export BUNDLE_TEMPLATE_MAG_DATABASE_MYSQL_ENABLED="${MAG_DATABASE_MYSQL_ENABLED:-true}"
