#!/usr/bin/env bash

#
#  Copyright (c) 2016 CA. All rights reserved.
#
#  This software may be modified and distributed under the terms
#  of the MIT license. See the LICENSE file for details.
#

. MAS-vars && . MAG-vars && . OTK-vars

HOSTNAME_ENCODED=$(echo -n "$BUNDLE_TEMPLATE_HOSTNAME" | base64)
PROTOCOL_HOSTNAME_ENCODED=$(echo -n "http://$BUNDLE_TEMPLATE_HOSTNAME" | base64)

export BUNDLE_TEMPLATE_HOSTNAME_ENCODED="${HOSTNAME_ENCODED}"
export BUNDLE_TEMPLATE_PROTOCOL_HOSTNAME_ENCODED="${PROTOCOL_HOSTNAME_ENCODED}"

compose_files=( MAS-docker-compose.yml MAS-links-docker-compose.yml MYSQL-docker-compose.yml DEV-CONSOLE-docker-compose.yml )

if [[ $MAS_MESSAGING_ENABLED == 'true' ]]; then
    compose_files+=( MAS-Messaging-links-docker-compose.yml MOSQUITTO-docker-compose.yml )
fi

args=""
for i in "${compose_files[@]}"
do
  args="${args} -f ${i}"
done

# Pull images via compose
if [[ (-z "${i}") || ( ! -z "${1}" && "${1}" == "pull") ]]; then
    echo "Pulling images for $args"
    docker-compose $args pull
fi

docker-compose $args rm -f -v
docker-compose $args up --force-recreate --abort-on-container-exit
docker-compose $args rm -f -v
