#!/usr/bin/env bash

. MAS-vars && . MAG-vars && . OTK-vars

compose_files=( MAS-docker-compose.yml MAS-links-docker-compose.yml MYSQL-docker-compose.yml MOSQUITTO-docker-compose.yml DEV-CONSOLE-docker-compose.yml )
args=""
for i in "${compose_files[@]}"
do
  args="${args} -f ${i}"
done

# Pull images via compose
if [[ (-z "${i}") || ( ! -z "${1}" && "${1}" == "pull") ]]; then
    echo "Pulling images for $args"
    docker-compose $args pull
fi

docker-compose $args rm -f -v
docker-compose $args up --force-recreate --abort-on-container-exit
docker-compose $args rm -f -v
