#!/usr/bin/env bash

#
#  Copyright (c) 2016 CA. All rights reserved.
#
#  This software may be modified and distributed under the terms
#  of the MIT license. See the LICENSE file for details.
#

export IMAGE_TAG=${IMAGE_TAG:-latest}
export IMAGE=${IMAGE:-caapimcollab/api-management-oauth:${IMAGE_TAG}}

export OTK_HOSTNAME="${OTK_HOSTNAME:-otk}"
export BUNDLE_TEMPLATE_OTK_HOSTNAME="${OTK_HOSTNAME}"

export BUNDLE_TEMPLATE_OTK_DATABASE_HOST="${OTK_DATABASE_HOST:-mysqldb}"
export BUNDLE_TEMPLATE_OTK_DATABASE_PORT="${OTK_DATABASE_PORT:-3306}"
export BUNDLE_TEMPLATE_OTK_DATABASE_USER="${OTK_DATABASE_USER:-db_admin}"
export BUNDLE_TEMPLATE_OTK_DATABASE_PASSWORD="${OTK_DATABASE_PASSWORD:-"UTWtziFHF0xgng=="}"
export BUNDLE_TEMPLATE_OTK_DATABASE_NAME="${OTK_DATABASE_NAME:-otk_db}"
export BUNDLE_TEMPLATE_OTK_DATABASE_TYPE="${OTK_DATABASE_TYPE:-mysql}"
export BUNDLE_TEMPLATE_OTK_DATABASE_MYSQL_ENABLED="${OTK_DATABASE_MYSQL_ENABLED:-true}"

export SSG_DATABASE_TYPE="${SSG_DATABASE:-derby}"
export SSG_DATABASE_DERBY_IN_MEMORY="${SSG_DATABASE_DERBY_IN_MEMORY:-true}"
export SSG_JVM_HEAP="${SSG_JVM_HEAP:-2G}"

export ADD_TEST_CLIENTS="${ADD_TEST_CLIENTS:-false}"

export SSG_CLUSTER_PASSWORD="${SSG_CLUSTER_PASSWORD:-"7layer"}"
if [ z"${SSG_CLUSTER_PASSWORD}" == z ]; then
	echo "SSG_CLUSTER_PASSWORD is required."
	exit 0
fi
